build:
  image: docker:19.03.1
  tags:
    - docker builder
  script:
    - export TAG_NAME=$CI_REGISTRY_IMAGE:${VERSION:-latest}
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --no-cache -t $TAG_NAME --build-arg VERSION=$VERSION .
    - docker push $TAG_NAME
  when: manual  
